name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install sphinx
      - name: Build html
        run: |
          make html
      - name: Deploy to GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0-alpha
        with:
          build_dir: build/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
