name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install sphinx
      - name: Build html
        run: |
          make html
          touch build/html/.nojekyll
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: build/html
          GH_PAT: ${{ secrets.GH_PAT }}
